# Conteúdo de `Cargo.toml`

adicione em typst-library/Cargo.toml


[package]
name = "typst-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }
